const Map<String,String>ar={
  'Products':'منتجات',
  'Profile':'الصفحه الشخصية',
  'product_Details':'تفاصيل المنتج',
  'Home':'الصفحة الرئيسية',
  'click':'يببييب',
  'LogIn':'تسجيل الدخول',
  'Sign Up':'انشاء حساب',
  'Phone':'الموبايل',
  "Email":'الايميل',
  "Password":'الرقم السري',
  'FirstName':'الاسم الاول',
  'LastName':'الاسم الاخير',
  'CreateNewAccount':'انشاء حساب جديد',
  'I Already Have An Account':'تسجيل الدخول',
  'Address':'العنوان',
  'Notification':'الاشعارات',
  'Location':'الموقع',
  'RTL':'اللغة',
  "Username":'الاسم',
  "Change Language":'تغيير اللغة',
  'Arabic':'العربية',
  'English':'الانجليزية',
  'Language':'اللغة',
  'Light Theme':'المظهر الفاتح',
  'Dark Theme':'المظهر الداكن',
  'Settings':'الاعدادات',
  'Log Out':'تسجيل الخروج',
  'Quantity':'الكمية'

};