const Map<String,String>en={
  'Products':'Products',
  'Profile':'Profile',
  'product_Details':'Product Details',
  'Home':'Home',
  'click':'click',
  'LogIn':'Log In',
  'Sign Up':'Sign Up',
  'Phone':'Phone',
  "Email":'Email',
  "Username":'Username',
  "Password":'Password',
  'FirstName':'First Name',
  'LastName':'Last Name',
  'CreateNewAccount':'Create New Account',
  'I Already Have An Account':'I Already Have An Account',
  'Address':'Address',
  'Notification':'Notification',
  'Location':'Location',
  'RTL':'RTL',
  "Change Language":'Change Language',
  'Arabic':'Arabic',
  'English':'English',
  'Language':'Language',
  'Light Theme':'Light Theme',
  'Dark Theme':'Dark Theme',
  'Settings':'Settings',
  'Log Out':'Log Out',
  'Quantity':'Quantity'

};